tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "autoconf"
brew "automake"
brew "coreutils"
brew "libtool"
brew "asdf"
brew "sqlite"
brew "xz"
brew "awscli"
brew "curl"
brew "docker", link: false
brew "fish"
brew "fzf"
brew "gettext"
brew "ghq"
brew "git"
brew "libffi"
brew "glib"
brew "libevent"
brew "gnupg"
brew "go"
brew "gradle"
brew "graphviz"
brew "helm"
brew "hub"
brew "jq"
brew "kubernetes-cli"
brew "lua"
brew "lua@5.1"
brew "luajit"
brew "mas"
brew "mercurial"
brew "ngrep"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "shellcheck"
brew "terraform"
brew "tig"
brew "tmux"
brew "wget"
cask "alfred"
cask "android-studio"
cask "appcleaner"
cask "bettertouchtool"
cask "day-o"
cask "docker"
cask "firefox"
cask "gimp"
cask "google-backup-and-sync"
cask "google-chrome"
cask "google-cloud-sdk"
cask "google-japanese-ime"
cask "intellij-idea"
cask "iterm2"
cask "java"
cask "karabiner-elements"
cask "keycastr"
cask "kindlegen"
cask "libreoffice"
cask "onyx"
cask "seashore"
cask "skype"
cask "virtualbox"
mas "Fotor Photo Editor", id: 503039729
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
